#!/bin/bash -xe

# redirect stderr
exec 2>&1

echo "Create postgres user that will run the db daemon"
exec useradd -m {{pkg.svc_user}} -G {{pkg.svc_group}}

echo "Create postres install directory and set permissions"
exec mkdir -pv {{pkg.svc_data_path}} && chown -Rv {{pkg.svc_user}}.{{pkg.svc_group}} {{pkg.svc_data_path}}

# echo "Update postgresql.conf (database configurations)"
# exec cp -v ${pkg.svc_config_path}/postgresql.conf {{pkg.svc_data_path}}/share

# echo "Update pga_hba.conf (authorities definition)"
# exec cp -v ${pkg.svc_config_path}/pga_hba.conf {{pkg.svc_data_path}}/share

echo "Initialize postgresql database"
exec pg_ctl initdb --pgdata {{pkg.svc_data_path}} \
                   --log {{cfg.log_path}} \
                   --mode {{cfg.shutdown_mode}} \
#                  -o "—-xlogdir={{cfg.wal_path}}" \
#                  "--username={{pkg.svc_user}}" \
#                  "--auth=<authmethod" \
#                  "-—auth-host=<authmethod>" \
#		           "--auth-local=<authmethod>" \
#		           "-—pwfile=" \
#                  "--locale=" \

echo "Checking status"
exec pg_ctl status
