#!{{pkgPathFor "core/bash"}}/bin/bash -xe

exec 2>&1

# TODO: symbolic link everything to the service var path


echo "Executing init hook"
source {{pkg.svc_config_path}}/helpers.sh

create_db_superuser
set_dir_permissions

if [[ ! -f "{{pkg.svc_data_path}}" ]]; then
    # echo "Update postgresql.conf (database configurations)"
    # cp -v ${pkg.svc_config_path}/postgresql.conf {{pkg.svc_data_path}}/share
    
    # echo "Update pga_hba.conf (authorities definition)"
    # cp -v ${pkg.svc_config_path}/pga_hba.conf {{pkg.svc_data_path}}/share
    
    echo "Database does not exist, creating with 'initdb'"
    chpst -U {{cfg.superuser.name}}:{{cfg.superuser.group}} \
	   -u {{cfg.superuser.name}}:{{cfg.superuser.group}}  \
   	initdb -U {{cfg.superuser.name}} \
                -E utf8 \
                -D {{pkg.svc_data_path}} \
                #--pwfile {{pkg.svc_config_path}}/pwfile \
                --locale POSIX \
                --data-checksums
fi


# echo "Initialize postgresql database"
# pg_ctl initdb --pgdata {{pkg.svc_data_path}} \
#                   --log {{cfg.log_path}} \
#                   --mode {{cfg.shutdown_mode}} \
#                  -o "—-xlogdir={{cfg.wal_path}}" \
#                  "--username={{pkg.svc_user}}" \
#                  "--auth=<authmethod" \
#                  "-—auth-host=<authmethod>" \
#		           "--auth-local=<authmethod>" \
#		           "-—pwfile=" \
#                  "--locale=" \

# echo "Checking status"
# pg_ctl status
