#!{{pkgPathFor "core/bash"}}/bin/bash -xe

exec 2>&1

echo "Executing run hook"

echo "Starting postgresql database service"
exec chpst -U {{cfg.superuser.name}} -u {{cfg.superuser.name}} \
        {{cfg.binpath}}/pg_ctl start -D {{cfg.db.datapath}}

